### ISSUE TITLE
Subscription failure "Server returned nothing (no headers, no data)" [Example 2]

### ISSUE THREAD

**Issue by daniel9029** [sonsoleslp/fiware-cosmos-orion-flink-connector-examples#4]
Good afternoon,

I'm having some issues following the Example 2 tutorial steps.  
After I solved some server connection problem (the port 9001 wasn't configured suitably in the config file), I've created the Room entity and then subscribed to the attributes changes.
But this last step gave me this error: 

orion          | time=Thursday 14 May 13:46:50 2020.723Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[454]:collectionUpdate | msg=Database Operation Successful (update: <{ _id: ObjectId('5ebd4b94a1d4397897f1e71e'), $or: [ { lastFailure: { $lt: 1589463956 } }, { lastFailure: { $exists: false } } ] }, { $set: { lastFailure: 1589463956, **lastFailureReason: "Server returned nothing (no headers, no data)"** } }>).

Here is the modified yml file:
version: '3.5'
services:
 mongo-db:
   image: mongo:3.6
   hostname: mongo-db
   container_name: db-mongo
   expose:
     - "27017"
   ports:
     - "27017:27017"
   networks:
     - default
   command: --bind_ip_all --smallfiles --nojournal
   volumes:
      - mongo-db:/data
 orion:
   image: fiware/orion:latest
   hostname: orion
   container_name: orion
   depends_on:
     - mongo-db
   networks:
     - default
   expose:
     - "1026"
   ports:
     - "1026:1026"
   command: -dbhost mongo-db -logLevel DEBUG
 jobmanager:
   image: flink:1.9.0-scala_2.11
   container_name: flink-jobmanager
   expose:
     - "6123"
   ports:
     - "8081:8081"
     - "9001:9001"
   command: jobmanager
   environment:
     - JOB_MANAGER_RPC_ADDRESS=jobmanager
 taskmanager:
   image: flink:1.9.0-scala_2.11
   hostname: taskmanager
   container_name: flink-taskmanager
   ports:
     - "6121:6121"
     - "6122:6122"
   depends_on:
     - jobmanager
   command: taskmanager
   links:
     - "jobmanager:jobmanager"
   environment:
     - JOB_MANAGER_RPC_ADDRESS=jobmanager

Thank you for your attention!

**Comment by sonsoleslp** [comment]
Hi,
Make sure your Flink job is running and that you have subscribed to notifications in Orion using the right callback URL. If the job is not running or the callback URL is unreachable, the notification will fail.

**Comment by daniel9029** [comment]
Hi,
thank you for the answer. Yes, the Flink job related to the Example2 is running (as you can see from the screenshot below)

![ApacheFlink](https://user-images.githubusercontent.com/65351413/82040222-8e0a5200-96a6-11ea-80e7-d7b4a483ceb5.png)

I can correctly submit a new entity with the script provided under **files/example2/curl_CreateNewEntity.sh**, but when I try to subscribe to the attributes change with the script under **files/example2/curl_SubscribeToEntityNotifications.sh**, this happens:

![orion_response](https://user-images.githubusercontent.com/65351413/82040883-91eaa400-96a7-11ea-8eac-8f3792575726.png)

![subscription_json](https://user-images.githubusercontent.com/65351413/82040907-9c0ca280-96a7-11ea-94cf-c0f688f25732.png)

Am I wrong in something?

Thank you again for your patience!

**Comment by sonsoleslp** [comment]
If you are using the Flink Job Manager then you are already on example 3. Try subscribing as it's done in this file:
https://github.com/ging/fiware-cosmos-orion-flink-connector-examples/blob/master/files/example3/curl_SubscribeToEntityNotifications.sh

**Comment by daniel9029** [comment]
Ok perfect, now it works fine :)

Thank you for your time!
